services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    environment:
      - PUID=${HL_USER}
      - PGID=${HL_GROUP}
      - TZ=${HL_TZ}
    volumes:
      - ${HL_CONFIG_FOLDER}/Prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped
    networks:
      - main

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    environment:
      - PUID=${HL_USER}
      - PGID=${HL_GROUP}
      - TZ=${HL_TZ}
    volumes:
      - ${HL_CONFIG_FOLDER}/Sonarr:/config
      - ${HL_DATA_FOLDER}/TV:/tv
      - ${HL_DATA_FOLDER}/Downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
    networks:
      - main

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    environment:
      - PUID=${HL_USER}
      - PGID=${HL_GROUP}
      - TZ=${HL_TZ}
    volumes:
      - ${HL_CONFIG_FOLDER}/Radarr:/config
      - ${HL_DATA_FOLDER}/Movies:/movies
      - ${HL_DATA_FOLDER}/Downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
    networks:
      - main

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    environment:
      - PUID=${HL_USER}
      - PGID=${HL_GROUP}
      - TZ=${HL_TZ}
    volumes:
      - ${HL_CONFIG_FOLDER}/Bazarr:/config
      - ${HL_DATA_FOLDER}/Movies:/movies
      - ${HL_DATA_FOLDER}/TV:/tv
    ports:
      - 6767:6767
    restart: unless-stopped
    networks:
      - main

  readarr:
    image: lscr.io/linuxserver/readarr:0.4.18-develop
    environment:
      - PUID=${HL_USER}
      - PGID=${HL_GROUP}
      - TZ=${HL_TZ}
    volumes:
      - ${HL_CONFIG_FOLDER}/Readarr:/config
      - ${HL_DATA_FOLDER}/Books:/books
      - ${HL_DATA_FOLDER}/Downloads:/downloads
    ports:
      - 8787:8787
    restart: unless-stopped
    networks:
      - main

  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    environment:
      - PUID=${HL_USER}
      - PGID=${HL_GROUP}
      - TZ=${HL_TZ}
    volumes:
      - ${HL_CONFIG_FOLDER}/Lidarr:/config
      - ${HL_DATA_FOLDER}/Music:/music
      - ${HL_DATA_FOLDER}/Downloads:/downloads
    ports:
      - 8686:8686
    restart: unless-stopped
    networks:
      - main

networks:
  main:
    name: main
    external: true
