services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    environment:
      - PUID=${HL_USER}
      - PGID=${HL_GROUP}
      - TZ=${HL_TZ}
    volumes:
      - ${HL_CONFIG_FOLDER}/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped
    networks:
      - main

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    environment:
      - PUID=${HL_USER}
      - PGID=${HL_GROUP}
      - TZ=${HL_TZ}
    volumes:
      - ${HL_CONFIG_FOLDER}/sonarr:/config
      - ${HL_DATA_FOLDER}:/data
    ports:
      - 8989:8989
    restart: unless-stopped
    networks:
      - main

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    environment:
      - PUID=${HL_USER}
      - PGID=${HL_GROUP}
      - TZ=${HL_TZ}
    volumes:
      - ${HL_CONFIG_FOLDER}/radarr:/config
      - ${HL_DATA_FOLDER}:/data
    ports:
      - 7878:7878
    restart: unless-stopped
    networks:
      - main

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    environment:
      - PUID=${HL_USER}
      - PGID=${HL_GROUP}
      - TZ=${HL_TZ}
    volumes:
      - ${HL_CONFIG_FOLDER}/bazarr:/config
      - ${HL_DATA_FOLDER}/media:/data/media
    ports:
      - 6767:6767
    restart: unless-stopped
    networks:
      - main

  readarr:
    image: lscr.io/linuxserver/readarr:0.4.18-develop
    environment:
      - PUID=${HL_USER}
      - PGID=${HL_GROUP}
      - TZ=${HL_TZ}
    volumes:
      - ${HL_CONFIG_FOLDER}/readarr:/config
      - ${HL_DATA_FOLDER}:/data
    ports:
      - 8787:8787
    restart: unless-stopped
    networks:
      - main

  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    environment:
      - PUID=${HL_USER}
      - PGID=${HL_GROUP}
      - TZ=${HL_TZ}
    volumes:
      - ${HL_CONFIG_FOLDER}/lidarr:/config
      - ${HL_DATA_FOLDER}:/data
    ports:
      - 8686:8686
    restart: unless-stopped
    networks:
      - main

networks:
  main:
    name: main
    external: true
