services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    environment:
      - PUID=${HL_USER}
      - PGID=${HL_GROUP}
      - TZ=${HL_TZ}
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - ${HL_CONFIG_FOLDER}/qbittorrent:/config
      - ${HL_DATA_FOLDER}/downloads:/downloads
    ports:
      - 8080:8080 # Web UI Port
      - 6881:6881 # Torrenting Port
      - 6881:6881/udp # Torrenting Port
    restart: unless-stopped
    networks:
      - main

  metube:
    image: ghcr.io/alexta69/metube
    environment:
      - UID=${HL_USER}
      - GID=${HL_GROUP}
    volumes:
      - ${HL_DATA_FOLDER}/downloads:/downloads
    ports:
      - 8081:8081
    restart: unless-stopped
    networks:
      - main

networks:
  main:
    name: main
    external: true
