services:
  homer:
    image: b4bz/homer
    environment:
      - PORT=7575
    volumes:
      - ${HL_CONFIG_FOLDER}/homer:/www/assets
    ports:
      - 7575:7575
    user: ${HL_USER}:${HL_GROUP}
    restart: unless-stopped
    networks:
      - main

  portainer:
    image: portainer/portainer-ce:lts
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HL_CONFIG_FOLDER}/portainer:/data
    ports:
      - 9443:9443
    restart: unless-stopped
    networks:
      - main

networks:
  main:
    name: main
    external: true
