services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    environment:
      - PUID=${USER}
      - PGID=${GROUP}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_FOLDER}/Prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped
    networks:
      - main

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    environment:
      - PUID=${USER}
      - PGID=${GROUP}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_FOLDER}/Sonarr:/config
      - ${DATA_FOLDER}/TV:/tv
      - ${DATA_FOLDER}/Downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
    networks:
      - main

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    environment:
      - PUID=${USER}
      - PGID=${GROUP}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_FOLDER}/Radarr:/config
      - ${DATA_FOLDER}/Movies:/movies
      - ${DATA_FOLDER}/Downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
    networks:
      - main

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    environment:
      - PUID=${USER}
      - PGID=${GROUP}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_FOLDER}/Bazarr:/config
      - ${DATA_FOLDER}/Movies:/movies
      - ${DATA_FOLDER}/TV:/tv
    ports:
      - 6767:6767
    restart: unless-stopped
    networks:
      - main

  readarr:
    image: lscr.io/linuxserver/readarr:0.4.18-develop
    environment:
      - PUID=${USER}
      - PGID=${GROUP}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_FOLDER}/Readarr:/config
      - ${DATA_FOLDER}/Books:/books
      - ${DATA_FOLDER}/Downloads:/downloads
    ports:
      - 8787:8787
    restart: unless-stopped
    networks:
      - main

  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    environment:
      - PUID=${USER}
      - PGID=${GROUP}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_FOLDER}/Lidarr:/config
      - ${DATA_FOLDER}/Music:/music
      - ${DATA_FOLDER}/Downloads:/downloads
    ports:
      - 8686:8686
    restart: unless-stopped
    networks:
      - main

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    environment:
      - PUID=${USER}
      - PGID=${GROUP}
      - TZ=${TZ}
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - ${CONFIG_FOLDER}/qBittorrent:/config
      - ${DATA_FOLDER}/Downloads:/downloads
    ports:
      - 8080:8080 # Web UI Port
      - 6881:6881 # Torrenting Port
      - 6881:6881/udp # Torrenting Port
    restart: unless-stopped
    networks:
      - main

  # plex:
  #   image: lscr.io/linuxserver/plex:latest
  #   environment:
  #     - PUID=${USER}
  #     - PGID=${GROUP}
  #     - TZ=${TZ}
  #     - VERSION=docker
  #     - PLEX_CLAIM=${PLEX_CLAIM}
  #   volumes:
  #     - ${CONFIG_FOLDER}/Plex:/config
  #     - ${DATA_FOLDER}/TV:/tv
  #     - ${DATA_FOLDER}/Movies:/movies
  #     - ${DATA_FOLDER}/Videos:/videos
  #     - ${DATA_FOLDER}/Photos:/photos
  #     - ${DATA_FOLDER}/Music:/music
  #   ports:
  #     - 32400:32400 # Web UI Port
  #     - 32469:32469 # Plex DLNA Server Port
  #     - 1900:1900/udp # Plex DLNA Server Port
  #   restart: unless-stopped
  #   networks:
  #     - main

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    environment:
      - PUID=${USER}
      - PGID=${GROUP}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_FOLDER}/Jellyfin:/config
      - ${DATA_FOLDER}/TV:/data/tvshows
      - ${DATA_FOLDER}/Movies:/data/movies
      - ${DATA_FOLDER}/Videos:/data/videos
      - ${DATA_FOLDER}/Photos:/data/photos
      - ${DATA_FOLDER}/Music:/data/music
    ports:
      - 8096:8096 # Web UI (HTTP)
      - 7359:7359/udp # Auto-discovery (LAN)
      - 1900:1900/udp # DLNA
    restart: unless-stopped
    networks:
      - main

  metube:
    image: ghcr.io/alexta69/metube
    environment:
      - UID=${USER}
      - GID=${GROUP}
    volumes:
      - ${DATA_FOLDER}/Downloads:/downloads
    ports:
      - 8081:8081
    restart: unless-stopped
    networks:
      - main

networks:
  main:
    name: main
    driver: bridge
