services:
  minecraft:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    environment:
      # https://docker-minecraft-server.readthedocs.io/en/latest/variables/#general-options
      - UID=${USER}
      - GID=${GROUP}
      - TZ=${TZ}
      # https://docker-minecraft-server.readthedocs.io/en/latest/variables/#server
      - EULA=TRUE
      - TYPE=VANILLA
      - VERSION=${MINECRAFT_VERSION}
      - DIFFICULTY=normal
    volumes:
      - ${CONFIG_FOLDER}/Minecraft:/data
    ports:
      - 25565:25565
    restart: unless-stopped
    networks:
      - main

networks:
  main:
    name: main
    external: true
