services:
  minecraft:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    environment:
      # https://docker-minecraft-server.readthedocs.io/en/latest/variables/#general-options
      - UID=${HL_USER}
      - GID=${HL_GROUP}
      - TZ=${HL_TZ}
      # https://docker-minecraft-server.readthedocs.io/en/latest/variables/#server
      - EULA=TRUE
      - TYPE=VANILLA
      - VERSION=${HL_MINECRAFT_VERSION}
      - DIFFICULTY=normal
    volumes:
      - ${HL_CONFIG_FOLDER}/minecraft:/data
    ports:
      - 25565:25565
    restart: unless-stopped
    networks:
      - main

networks:
  main:
    name: main
    external: true
