services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    environment:
      - PUID=${HL_USER}
      - PGID=${HL_GROUP}
      - TZ=${HL_TZ}
    volumes:
      - ${HL_CONFIG_FOLDER}/jellyfin:/config
      - ${HL_DATA_FOLDER}/media:/data/media
    ports:
      - 8096:8096 # Web UI (HTTP)
      - 7359:7359/udp # Auto-discovery (LAN)
      - 1900:1900/udp # DLNA
    restart: unless-stopped
    networks:
      - main

networks:
  main:
    name: main
    external: true
